language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
env:
  - DEPS=false
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
script:
  - echo 'done'
