language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
notifications:
  email: false
env:
  - DEPS=false
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
script:
  - echo 'done'
