language: python
python:
  - 3.3
notifications:
  email: false
env:
  - DEPS=false
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
script:
  - "python setup.py nosetests -v --with-cover"
