#!/usr/bin/env python
# vim:syntax=python
# sfc - cli to salesforce api
from pprint import pprint
from sforce import COMMONS as c
from sforce.util import Struct
from sforce.client import sf_session
from sforce.models import sf_obj_get, sf_obj_describe, sf_obj_update
import os

if __name__=="__main__":
    c['sandbox'] = True
    c['client_key'] = os.environ['SFKEY']
    c['client_secret'] = os.environ['SFSECRET']
    # Intialize session
    sf_session(c)
    ret, res = sf_obj_get(c, '001M000000P0UzbIAF', 'Account')
    pprint(res, indent=2)
    pprint(res.Id)
    pprint(res.attributes.type)
    pprint(res.attributes.url)
    pprint(res.BillingCity)
